/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab03;

import javax.swing.ImageIcon;

/**
 *
 * @author WILME
 */
public class PantallaFinal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public PantallaFinal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Marcadores");
        this.setIconImage(new ImageIcon(getClass().getResource("Imagenes/LogoDM.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumPuntaje = new javax.swing.JLabel();
        PuntajeLbl = new javax.swing.JLabel();
        NombreLbl = new javax.swing.JLabel();
        ResumenLbl = new javax.swing.JLabel();
        MarcadoresBtn = new javax.swing.JButton();
        VolverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPuntaje = new javax.swing.JTable();
        FondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(730, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumPuntaje.setFont(new java.awt.Font("Malgun Gothic", 1, 34)); // NOI18N
        NumPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        NumPuntaje.setText("###");
        getContentPane().add(NumPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        PuntajeLbl.setFont(new java.awt.Font("Malgun Gothic", 1, 34)); // NOI18N
        PuntajeLbl.setForeground(new java.awt.Color(255, 255, 255));
        PuntajeLbl.setText("Tu Puntaje:");
        getContentPane().add(PuntajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        NombreLbl.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(255, 255, 255));
        NombreLbl.setText("Nombre");
        getContentPane().add(NombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        ResumenLbl.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        ResumenLbl.setForeground(new java.awt.Color(255, 255, 255));
        ResumenLbl.setText("Resumen:");
        getContentPane().add(ResumenLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        MarcadoresBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        MarcadoresBtn.setForeground(new java.awt.Color(255, 255, 255));
        MarcadoresBtn.setText("Marcadores >");
        MarcadoresBtn.setBorderPainted(false);
        MarcadoresBtn.setContentAreaFilled(false);
        MarcadoresBtn.setDefaultCapable(false);
        MarcadoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadoresBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MarcadoresBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        VolverBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        VolverBtn.setForeground(new java.awt.Color(255, 255, 255));
        VolverBtn.setText("< Volver");
        VolverBtn.setBorderPainted(false);
        VolverBtn.setContentAreaFilled(false);
        VolverBtn.setDefaultCapable(false);
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        TablaPuntaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaPuntaje);
        if (TablaPuntaje.getColumnModel().getColumnCount() > 0) {
            TablaPuntaje.getColumnModel().getColumn(0).setResizable(false);
            TablaPuntaje.getColumnModel().getColumn(1).setResizable(false);
            TablaPuntaje.getColumnModel().getColumn(2).setResizable(false);
            TablaPuntaje.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 260));

        FondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcadoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadoresBtnActionPerformed
        new VentanaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MarcadoresBtnActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JButton MarcadoresBtn;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JLabel NumPuntaje;
    private javax.swing.JLabel PuntajeLbl;
    private javax.swing.JLabel ResumenLbl;
    private javax.swing.JTable TablaPuntaje;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
