/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab03;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WILME
 */
public class PantallaFinal extends javax.swing.JFrame {

    public int NumPregunta;
    public MultiList<Boolean> multiList;
    public LinkedList<Integer> RespuestasTurno;

    public PantallaFinal(int NumPregunta, MultiList multiList, LinkedList RespuestasTurno) {
        this.multiList = multiList;
        this.RespuestasTurno = RespuestasTurno;
        initComponents();
        NumPuntaje.setText(String.valueOf(NumPregunta));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Marcadores");
        this.setIconImage(new ImageIcon(getClass().getResource("Imagenes/LogoDM.png")).getImage());

        DefaultTableModel model = (DefaultTableModel) TablaPuntaje.getModel();
        model.setColumnCount(3); // Establecer el número de columnas en 3

        for (int i = 0; i < multiList.size(); i++) {
            ArrayList<Boolean> sublist = this.multiList.getSublist(i);
            for (int j = 0; j < sublist.size(); j++) {
                String acierto;
                if (sublist.get(j)) {
                    acierto = "Correcto";
                } else {
                    acierto = "Error";
                }
                model.addRow(new Object[]{i * 4 + j + 1, RespuestasTurno.get(i * 20 + j), acierto});
            }
        }

    }

    private void guardarEnArchivo() {
        try {
            String filePath = "Marcadores.txt"; // Reemplaza con la ruta completa
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true));

            String respuestaTurnoSize = RespuestasTurno != null ? String.valueOf(RespuestasTurno.size()) : "0";
            String respuestasAcertadas = String.valueOf(contarRespuestasAcertadas());

            writer.write(RespuestaDada.getText() + "\t" + respuestaTurnoSize + "\t" + respuestasAcertadas + "\n");
            writer.close();
            System.out.println("Nuevo registro de marcadores guardado correctamente.");
        } catch (IOException e) {
            System.out.println("Ocurrió un error al guardar el nuevo registro de marcadores en el archivo.");
            e.printStackTrace();
        }
    }

    private int contarRespuestasAcertadas() {
        int contador = 0;
        if (multiList.isMultiListEmpty()) {
            contador = 0;
        } else {
            for (int i = 0; i < multiList.size(); i++) {
                List<Boolean> sublist = multiList.getSublist(i);
                for (Boolean acierto : sublist) {
                    if (acierto) {
                        contador++;
                    }
                }
            }
        }
        return contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        RespuestaDada = new javax.swing.JTextArea();
        NumPuntaje = new javax.swing.JLabel();
        PuntajeLbl = new javax.swing.JLabel();
        NombreLbl = new javax.swing.JLabel();
        ResumenLbl = new javax.swing.JLabel();
        MarcadoresBtn = new javax.swing.JButton();
        VolverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPuntaje = new javax.swing.JTable();
        FondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(730, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        RespuestaDada.setColumns(1);
        RespuestaDada.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        RespuestaDada.setRows(1);
        RespuestaDada.setTabSize(1);
        RespuestaDada.setToolTipText("");
        jScrollPane2.setViewportView(RespuestaDada);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 230, 40));

        NumPuntaje.setFont(new java.awt.Font("Malgun Gothic", 1, 34)); // NOI18N
        NumPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        NumPuntaje.setText("###");
        getContentPane().add(NumPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        PuntajeLbl.setFont(new java.awt.Font("Malgun Gothic", 1, 34)); // NOI18N
        PuntajeLbl.setForeground(new java.awt.Color(255, 255, 255));
        PuntajeLbl.setText("Tu Puntaje:");
        getContentPane().add(PuntajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        NombreLbl.setFont(new java.awt.Font("Malgun Gothic", 1, 30)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(255, 255, 255));
        NombreLbl.setText("Nombre:");
        getContentPane().add(NombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        ResumenLbl.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        ResumenLbl.setForeground(new java.awt.Color(255, 255, 255));
        ResumenLbl.setText("Resumen:");
        getContentPane().add(ResumenLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        MarcadoresBtn.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        MarcadoresBtn.setForeground(new java.awt.Color(255, 255, 255));
        MarcadoresBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/puntuacion-mas-alta.png"))); // NOI18N
        MarcadoresBtn.setText("Marcadores >");
        MarcadoresBtn.setBorderPainted(false);
        MarcadoresBtn.setContentAreaFilled(false);
        MarcadoresBtn.setDefaultCapable(false);
        MarcadoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadoresBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MarcadoresBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 260, 80));

        VolverBtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        VolverBtn.setForeground(new java.awt.Color(255, 255, 255));
        VolverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/regreso-facil (2).png"))); // NOI18N
        VolverBtn.setText("  ");
        VolverBtn.setAlignmentX(500.0F);
        VolverBtn.setAlignmentY(25.0F);
        VolverBtn.setBorder(null);
        VolverBtn.setBorderPainted(false);
        VolverBtn.setContentAreaFilled(false);
        VolverBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VolverBtn.setDefaultCapable(false);
        VolverBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        VolverBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VolverBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VolverBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 70));

        TablaPuntaje.setAutoCreateRowSorter(true);
        TablaPuntaje.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        TablaPuntaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Pregunta", "Respuesta", "Acierto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPuntaje.setEnabled(false);
        TablaPuntaje.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TablaPuntaje);
        if (TablaPuntaje.getColumnModel().getColumnCount() > 0) {
            TablaPuntaje.getColumnModel().getColumn(0).setResizable(false);
            TablaPuntaje.getColumnModel().getColumn(1).setResizable(false);
            TablaPuntaje.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 500, 260));

        FondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcadoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadoresBtnActionPerformed
        guardarEnArchivo();
        new Marcadores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MarcadoresBtnActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        new VentanaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaFinal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MultiList<Boolean> multiList1 = new MultiList<>();
                List<Boolean> sublist1 = new ArrayList<>();
                multiList1.addSublist(sublist1);
                LinkedList linkedL1 = new LinkedList<>();
                LinkedList linked1 = null;
                new PantallaFinal(0, multiList1, linked1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JButton MarcadoresBtn;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JLabel NumPuntaje;
    private javax.swing.JLabel PuntajeLbl;
    private javax.swing.JTextArea RespuestaDada;
    private javax.swing.JLabel ResumenLbl;
    private javax.swing.JTable TablaPuntaje;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
