/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab03;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import lab03.Logica;

/**
 *
 * @author WILME
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Principal");
        this.setIconImage(new ImageIcon(getClass().getResource("Imagenes/LogoDM.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        MarcadoresBtn = new javax.swing.JButton();
        JugarBtn = new javax.swing.JButton();
        Img3 = new javax.swing.JLabel();
        Img1 = new javax.swing.JLabel();
        Img2 = new javax.swing.JLabel();
        FondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(730, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Desafio Matemático");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        MarcadoresBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        MarcadoresBtn.setForeground(new java.awt.Color(255, 255, 255));
        MarcadoresBtn.setText("Marcadores");
        MarcadoresBtn.setBorderPainted(false);
        MarcadoresBtn.setContentAreaFilled(false);
        MarcadoresBtn.setDefaultCapable(false);
        MarcadoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadoresBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MarcadoresBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        JugarBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        JugarBtn.setForeground(new java.awt.Color(255, 255, 255));
        JugarBtn.setText("Jugar");
        JugarBtn.setBorderPainted(false);
        JugarBtn.setContentAreaFilled(false);
        JugarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(JugarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        Img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/Imagen7.png"))); // NOI18N
        getContentPane().add(Img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 200, 140));

        Img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/Numeros2.png"))); // NOI18N
        Img1.setToolTipText("");
        Img1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Img1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(Img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 250, 240));

        Img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/signosNew3.png"))); // NOI18N
        getContentPane().add(Img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 240));

        FondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab03/Imagenes/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JugarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarBtnActionPerformed
        Logica logica = new Logica();
        String[] vector = logica.operacioneslvl1(1);
        String Pregunta= vector[0];
        int Respuesta= Integer.parseInt(vector[1]);
        MultiList<Boolean> multiList = new MultiList<>();
        List<Boolean> sublist1 = new ArrayList<>();
        multiList.addSublist(sublist1);
        LinkedList linkedL = new LinkedList<>(); 
        new NivelesS(0, Pregunta, Respuesta, 1, multiList,linkedL).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JugarBtnActionPerformed

    private void MarcadoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadoresBtnActionPerformed
        new Marcadores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MarcadoresBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img2;
    private javax.swing.JLabel Img3;
    private javax.swing.JButton JugarBtn;
    private javax.swing.JButton MarcadoresBtn;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    void setTitle(int a) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
